server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}


management:
  tracing:
    sampling:
      probability: 1.0
    endpoint:
      health:
        probes:
          enabled: true
  endpoints:
    web:
      exposure:
        include: health,env,metrics,beans,loggers,football,prometheus